### ISSUE TITLE
Анимация Эдмунда

### ISSUE THREAD

**Issue by emustafin** [mafh/thingyfy#3]
Нужно анимировать картинку с Эдмундом по формату чата. Т.е. сначала появляется только аватар со строкой "Edmund is typing…", затем выползают сообщения.

**Comment by mafh** [comment]
Добавил анимацию диалога. Стартует при попадании во вьпорт.

**Comment by emustafin** [comment]
Нужно добавить анимацию для «…»

**Comment by mafh** [comment]
Троеточик заанимировано
