### ISSUE TITLE
Проверить везде интерлиньяж в меню, должен соответствовать 30

### ISSUE THREAD

**Issue by emustafin** [mafh/thingyfy#7]

**Comment by mafh** [comment]
Что такое 30?
Я смотрю глазами и не вижу разницы.

**Comment by mafh** [comment]
По поводу везде: интерлиньяж зависит от размера текста. Визуально, в заголовках он совпадет с макетом.
По меню - добавил отступы через паддинг, т.к. интерлиньяж должен быть меньше отступов между пунктами при возможных переносах строк.
Закрываем?
